// SPDX-License-Identifier: AGPL-3.0-only

pub const BOT_NAMES: &[&str] = &[
  "Adam",
  "Adam Link",
  "Alfie",
  "Alojzy Kukuryk",
  "Alpha 5",
  "Alpha 6",
  "Alpha 7",
  "Alsatia Zevo",
  "AMEE",
  "Ancient Ore Crusher",
  "Andrew",
  "Andromon",
  "Aniel",
  "Arale",
  "Artificial Friend",
  "Astor",
  "Astro Boy",
  "Atmophytes",
  "AUTO",
  "Automaton",
  "Ava and Kyoko",
  "A.X.L.",
  "B166ER",
  "B-4",
  "B.A.T.s",
  "Baymax",
  "BB-8",
  "B.E.N.",
  "Bender",
  "Beta-Machine",
  "Billybot",
  "Bishop",
  "Bocoe",
  "Boilerplate",
  "Bokkun",
  "Boppers",
  "Bors",
  "Brackenridge",
  "Brainbots",
  "Buffybot",
  "Byron",
  "C-16",
  "C-17",
  "C-18",
  "C-19",
  "Calculators",
  "Cambot",
  "Candy Droober",
  "Canti",
  "C.A.R.R.",
  "Casandra Kresnov",
  "CASE",
  "Cast-Iron Man",
  "CHAPPiE",
  "Cherry 2000",
  "CHIP",
  "Chitti",
  "Chuck the Robot",
  "Chucky",
  "Chumblies",
  "Clunk",
  "Coconuts",
  "Coldfire",
  "Coldstone",
  "Conky 2000",
  "Coyote",
  "Crow T. Robot",
  "Cutie",
  "Cyber Shredder",
  "Cylons",
  "Damon",
  "Darkhawks",
  "D.A.R.Y.L.",
  "D.A.V.E.",
  "David 8",
  "Dee Model",
  "Demerzel",
  "Docoe",
  "DOR-15",
  "Dorfl",
  "Dot Matrix",
  "Doyle",
  "DRN-0167",
  "Dr. Wallace Damon",
  "DV-8",
  "ED-209",
  "EDI",
  "Eighter",
  "Electric Grandmother",
  "Elio",
  "Emma-2",
  "Enforcer Drone",
  "Engimals",
  "EVE",
  "Ez-27",
  "Franklin Droober",
  "Freya",
  "Freysa",
  "G2",
  "Gabriel",
  "GERTY 3000",
  "Giant Robo",
  "Giddy",
  "Gigantor",
  "GIR",
  "Glowboo",
  "Gnut",
  "Goddard",
  "Golden Army",
  "Gort",
  "Grounder",
  "G.U.A.R.D.O.",
  "Guardromon",
  "Gypsy",
  "Hadaly",
  "Hangman",
  "Haro",
  "HCR-328 and Tom",
  "Helena",
  "Helen O'Loy",
  "H.E.L.P.eR.",
  "Huggy",
  "Humanoids",
  "Intergalactic Advocate Bob",
  "Iron Giant",
  "Iron Man",
  "J20",
  "Jay-Dub",
  "Jenkins",
  "Jenny Wakeman",
  "Jinx",
  "Johnny 5",
  "Johnny Cab",
  "K-2SO",
  "K9",
  "Karaibots",
  "KARR",
  "Kay-Em 14",
  "Kikaider",
  "Killbots",
  "Kirby",
  "KITT",
  "Klapaucius",
  "Krybots",
  "Kryten",
  "L3-37",
  "L-76",
  "Lenny",
  "Leon Kowalski",
  "M3Gan",
  "Mac",
  "Machine Empire Blue Senturion",
  "Mackenzie Hartford",
  "Manders",
  "Mandroid",
  "Mariette",
  "Marius",
  "MARK13",
  "Marvin",
  "Mary 25",
  "Maureen Droober",
  "Max 404 and Cassandra One",
  "MD 63",
  "Mechagodzilla",
  "Mecha-King Ghidorah",
  "Mechanical Hound",
  "Mech Eagles",
  "Mechonoids",
  "MecWilly",
  "Megazords",
  "Melfina",
  "Metal giants",
  "Metal men",
  "Mildred the Maid",
  "Misery Company",
  "Miyu Greer",
  "MM7",
  "Moravecs",
  "Mordel",
  "Morgan",
  "Mr. Split",
  "Mr. Static",
  "Neotnia",
  "Newman",
  "Nimani",
  "Nimrod",
  "Nimue Alban",
  "Norby",
  "Okra",
  "Olimpia",
  "Olympia",
  "Omnidroid",
  "OX King",
  "Pax Magelanic",
  "Phatasaur",
  "Pino Petto",
  "Pixal",
  "P.O.P.S",
  "Primus",
  "Pris",
  "Project 2501",
  "Psycho Rangers",
  "Quinn",
  "R4-P17",
  "Rabbot",
  "Rachael",
  "Radius",
  "R.A.L.F",
  "R. Daneel Olivaw",
  "R. Dorothy Wayneright",
  "Recognizers",
  "Replicators",
  "Rex",
  "R. Giskard Reventlov",
  "RIA",
  "R.I.C. 2.0",
  "Richard Daniel",
  "Rick Deckard",
  "Robbie",
  "Robby the Robot",
  "Robi",
  "Rob-Monkey",
  "Robo",
  "RoboGadget",
  "Robositter",
  "Robot 7",
  "Robot B-9 Robotoid Robot",
  "Robotboy",
  "Robot Jones",
  "Roboto",
  "Roderick",
  "Rommie",
  "Rosie the Maid",
  "R.O.T.O.R.",
  "Roy Batty",
  "ROZZUM unit 7134",
  "S1MONE",
  "Sapper Morton",
  "S.A.R.-003",
  "Scratch",
  "Sergeant Metallic",
  "Setaur",
  "Sheila",
  "Sheriff Not-a-Robot",
  "SHROUD",
  "SI-9",
  "Sico",
  "SID 6.7",
  "SIMON",
  "Slim John",
  "Smiley the Robot",
  "Solo",
  "Sonny+ NS4",
  "S.O.P.H.I.E",
  "Sox",
  "Speedy",
  "Spofforth",
  "Spot",
  "Steel",
  "Stitchpunks",
  "Sulla",
  "Syder robots",
  "T-1000",
  "T-800",
  "T-850",
  "Tachikoma",
  "Talkie Toaster",
  "TARS",
  "T-Bob",
  "Techno Trousers",
  "Terminator",
  "Terminatrix",
  "Terminus",
  "Tet",
  "Toaster",
  "Tom Servo",
  "Tony",
  "Trace Mayter",
  "Trurl",
  "T-X",
  "Ultron",
  "Ulyssses",
  "UniBlab",
  "US 47",
  "Valerie 23",
  "Vision",
  "Voltron",
  "WALL-E",
  "Walter One",
  "Weebo",
  "XJ-9",
  "Yod",
  "Z-1",
  "Z-2",
  "Z-3",
  "Zane",
  "Zane Gort",
  "Zat",
  "Zeta",
  "Zhora",
  "Zoromes",
];
